### ISSUE TITLE
神奇海洋

### ISSUE THREAD

**Issue by xiaowei456** [buddingworld/XQuickEnergy#1]
### 增强类型

功能型增强

### 具体描述

能否能加个筛选选择的开关，能屏蔽些不想偷版图的人员，像水晶那样。

**Comment by buddingworld** [comment]
这个工作量对小白来说有点压力，可以往作者那反应试试😂

**Comment by xiaowei456** [comment]
加你个微信可以吗，一直用你的多号模式，方便能量雨护送，不过你有时更新不及时🙃
