### ISSUE TITLE
关闭收集能量后还是收集能量

### ISSUE THREAD

**Issue by xiaowei456** [buddingworld/XQuickEnergy#2]
### 程序版本 / 框架版本 / 模块版本

LSpatch

### 系统版本 / Android版本

鸿蒙4.0

### 详细描述问题发生的具体原因

切换小号后，本来关闭收集能量的，不过还是把自己和别的小号的能量收集了。

### 提供模块问题 Log 或必要 Log

没有，不会弄这个

**Comment by buddingworld** [comment]
试下刚更新的fix，之前作者的更新导致出现这个纰漏，我也纳闷了好久，才修复重新上传了呢。
