### ISSUE TITLE
一键收取能量开关打开了保存不了

### ISSUE THREAD

**Issue by WskDnpl** [buddingworld/XQuickEnergy#3]
### 程序版本 / 框架版本 / 模块版本

Lspatch

### 系统版本 / Android版本

Android 14

### 详细描述问题发生的具体原因

一键收取能量开关打开了保存不了，返回去查看还是关闭的

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by buddingworld** [comment]
漏了行，已补上
