### ISSUE TITLE
一键收取

### ISSUE THREAD

**Issue by xiaowei456** [buddingworld/XQuickEnergy#4]
### 程序版本 / 框架版本 / 模块版本

Lsp

### 系统版本 / Android版本

鸿蒙

### 详细描述问题发生的具体原因

一键收取打开保存后，总是自动的自己关闭
![Screenshot_20240223_080904_pansong291 xposed quickenergy repair](https://github.com/buddingworld/XQuickEnergy/assets/151404137/ab8de37f-9191-46b6-809f-83a465df70a4)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by buddingworld** [comment]
昨天补上了，在最新release里
