### ISSUE TITLE
周一复活能量顺序

### ISSUE THREAD

**Issue by WskDnpl** [buddingworld/XQuickEnergy#5]
### 增强类型

功能型增强

### 具体描述

周一复活能量能不能优先复活小号的呢

**Comment by buddingworld** [comment]
问题是设置了复活那些这些，然后程序怎么知道哪些是小号😂

**Comment by WskDnpl** [comment]
> 问题是设置了复活那些这些，然后程序怎么知道哪些是小号😂

可以按勾选顺序
