### ISSUE TITLE
这个版本跟上个版本设置打不开会黑屏

### ISSUE THREAD

**Issue by WskDnpl** [buddingworld/XQuickEnergy#6]
### 程序版本 / 框架版本 / 模块版本

Lspatch

### 系统版本 / Android版本

Android14

### 详细描述问题发生的具体原因

有些人的能量不会收取，是扫描不到吗

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by WskDnpl** [comment]
因为有些人的能量不收取，然后我重装了支付宝跟芝麻粒，然后发现芝麻粒的设置打不开，支付宝会卡死，测试了这个版本跟上个版本都这样，上上个版本没问题

**Comment by buddingworld** [comment]
有没有试过先把xqe目录改掉看看，看是不是权限问题。

**Comment by WskDnpl** [comment]
> 有没有试过先把xqe目录改掉看看，看是不是权限问题。

可能是权限问题，因为单独一个芝麻粒设置也打不开，我测试了内置支付宝，支付宝会卡启动界面，芝麻粒设置打不开，黑屏闪退。卸载支付宝，（卸载了支付宝，里面的 xqe 文件夹会跟着删除的） 重装芝麻粒，芝麻粒设置也打不开。然后我又下载上上个版本的芝麻粒是可以打开的。

**Comment by buddingworld** [comment]
我这没这个问题，尽量权限都给了再试试吧，不然试试原版的，这部分没有改动的。

**Comment by WskDnpl** [comment]
> 我这没这个问题，尽量权限都给了再试试吧，不然试试原版的，这部分没有改动的。

很奇怪，权限都给了的，原版没问题，之前安装的时候没有这个问题，就是发现有些能量会漏收想重装下然后就不行了
