### ISSUE TITLE
1.5.0是不是启动不了啊？我一启动支付宝就提示芝麻关门

### ISSUE THREAD

**Issue by Xr267** [buddingworld/XQuickEnergy#8]
### 程序版本 / 框架版本 / 模块版本

1.5.0 主程序 10.6.20.8000

### 系统版本 / Android版本

Android 14

### 详细描述问题发生的具体原因

换成1.4.5就可以，用了作者您的去弹窗版1.5.0也不行

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by buddingworld** [comment]
检查下配置和文件读取权限？我这两个都正常

**Comment by buddingworld** [comment]
150版本需要root才可以使用，本地，内置已经不可以使用，可以降级到145正常使用

群的公告哦，估计因为这个

**Comment by Xr267** [comment]
> 150版本需要root才可以使用，本地，内置已经不可以使用，可以降级到145正常使用
> 
> 群的公告哦，估计因为这个

原来这样，了解了，谢谢，主要现在大佬的github无法访问，没办法了解第一手动态😅
